[package]
name = "wgpu-native"
version = "0.0.0"
authors = [
	"Dzmitry Malyshau <kvark@mozilla.com>",
	"Joshua Groves <josh@joshgroves.com>",
	"Noah Charlton <ncharlton002@gmail.com>",
	"Almar Klein <almar@almarklein.org>",
	"Rajesh Malviya <rajveer0malviya@gmail.com>",
]
edition = "2021"
description = "Native WebGPU implementation based on wgpu-core"
homepage = "https://github.com/gfx-rs/wgpu-native"
repository = "https://github.com/gfx-rs/wgpu-native"
keywords = ["graphics"]
license = "MIT OR Apache-2.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[workspace]
members = ["."]
default-members = ["."]
resolver = "2"

[workspace.dependencies.wgpu]
package = "wgpu"
git = "https://github.com/davnotdev/wgpu"
branch = "godot-webgpu"
default-features = false

[workspace.dependencies.wgt]
package = "wgpu-types"
git = "https://github.com/davnotdev/wgpu"
branch = "godot-webgpu"

[workspace.dependencies.naga]
package = "naga"
git = "https://github.com/davnotdev/wgpu"
branch = "godot-webgpu"

[lib]
crate-type = ["cdylib", "staticlib"]

[features]
# TODO:
default = ["spirv", "glsl", "wgsl"]

#! ### Backends
# --------------------------------------------------------------------
#! ⚠️ WIP: Not all backends can be manually configured today.
#! On Windows, Linux & Android the Vulkan & GLES backends are always enabled.
#! See [#3514](https://github.com/gfx-rs/wgpu/issues/3514) for more details.

# TODO:

## Enables the DX12 backend on Windows.
# dx12 = ["wgc/dx12"]

## Enables the Metal backend on macOS & iOS.
# metal = ["wgc/metal"]

## Enables the GLES backend via [ANGLE](https://github.com/google/angle) on macOS using.
# angle = ["wgc/gles"]

## Enables the Vulkan backend on macOS & iOS.
# vulkan-portability = ["wgc/vulkan"]

#! **Note:** In the documentation, if you see that an item depends on a backend,
#! it means that the item is only available when that backend is enabled _and_ the backend
#! is supported on the current platform.

#! ### Shading language support
# --------------------------------------------------------------------

## Enable accepting SPIR-V shaders as input.
spirv = ["naga/spv-in"]

## Enable accepting GLSL shaders as input.
glsl = ["naga/glsl-in"]

## Enable accepting WGSL shaders as input.
wgsl = ["wgpu/wgsl"]

[dependencies.wgpu]
workspace = true
features = ["std", "parking_lot", "webgpu", "wgsl", "naga-ir"]

[dependencies.wgt]
workspace = true

[dependencies.naga]
workspace = true
optional = true

[dependencies.serde]
version = "1"
optional = true

[dependencies]
raw-window-handle = "0.6.0"
paste = "1"
log = "0.4"
thiserror = "2"
parking_lot = "0.12"
smallvec = "1"
bitflags = "2"

[build-dependencies]
bindgen = "0.72"
